version: '3.8'
services:
  bolt-assistant:
    build: .
    image: bolt-assistant:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000x